default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: grimoire_development
  username: <%= ENV['PGUSER'] || 'postgres' %>
  password: <%= ENV['PGPASSWORD'] || '' %>
  host: <%= ENV['PGHOST'] || 'localhost' %>
  port: <%= ENV['PGPORT'] || 5432 %>

test:
  <<: *default
  database: grimoire_test
  username: <%= ENV['PGUSER'] || 'postgres' %>
  password: <%= ENV['PGPASSWORD'] || '' %>
  host: <%= ENV['PGHOST'] || 'localhost' %>
  port: <%= ENV['PGPORT'] || 5432 %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
